### ISSUE TITLE
Incorrect password gives a daemon connect error

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/desktop-xamarin#10]
Upon opening up a wallet file with a password, if you fill in the password incorrectly, instead of alerting about an incorrect password, instead the wallet will show that it is attempting to connect to the daemon, and will then fail after 15 attempts.

If you open up the walletd.txt log and scroll to the bottom, you will see that it failed to open the wallet due to a wrong password.

This can be a bit confusing for new users who might think the software is buggy when they typo their password.

**Comment by codingwithredbull** [comment]
- Open and close container before connection to see if password is correct before continuing.
- Next update

Thanks!

**Comment by SolarstormTM** [comment]
I can't open the wallet file with the right password in the newest version.
My pw comes from a KeePass copy paste and the wallet opens with the old version (1.0.660) and won't open in the newest version, same error as described here.
Maybe somekind of character conversion?
My pw contains A-Z a-z 0-9 and Specials like ! $%& etc. German Windows.

**Comment by knightjdr** [comment]
I've been trying some different passwords when creating wallets. I can enter any password I want when creating the wallet but some won't let me log back in. Passwords that are 30 characters don't work at all, even if they only contain letters and numbers. A 15 character password of letters and numbers does work though.

My wallet version is 1.0.6617.7653.

**Comment by Square2k1** [comment]
I Have a similar issue me password has a   .   in it and i get the Deamon Connect Error   followed by a pop up saying : 

Deamon Connection Failed : MAXTRYERROR: No RPC connection/Failed

**Comment by codingwithredbull** [comment]
should be resolved with version 1.0.6625.36022. Please use the latest version, and reopen the ticket if the issue persists. Thanks!
