### ISSUE TITLE
Error occured on send. The operation has timed out.

### ISSUE THREAD

**Issue by taiyoukun** [turtlecoin/desktop-xamarin#13]
While trying to send TRTLs on the GUI Wallet

**Comment by codingwithredbull** [comment]
This is a result of the RPC daemon not responding. Please attempt your action again and upload the last few lines in your walletd.log, if a simple restart doesn't fix this

**Comment by codingwithredbull** [comment]
should be resolved with version 1.0.6625.36022. Please use the latest version, and reopen the ticket if the issue persists. Thanks!
