### ISSUE TITLE
Payment ID Needed

### ISSUE THREAD

**Issue by isonx** [turtlecoin/desktop-xamarin#2]
Payment Id is needed to sent turtle coin to the market (currently tradeogre.com)
I tried sending several amount of turtle coins to the market but haven't received the coins in my account in the market, because no payment id was stated. The GUI interface is only have the payment address to put and it has no payment id place to put. How to fix it? Thanks

**Comment by codingwithredbull** [comment]
Next update coming!

Please contact Tradeorge by twitter for help with previous TRX.

Sorry, we didn't know this would be needed prior to creating the wallet

**Comment by codingwithredbull** [comment]
Added last update
