### ISSUE TITLE
latest release 1.0.6625.36022 Deamon connection failed: unable to keep deamon connection up!

### ISSUE THREAD

**Issue by Square2k1** [turtlecoin/desktop-xamarin#21]
installed and selected existing walletid 

entered password and get the error:

Deamon connection failed: unable to keep deamon connection up!

**Comment by codingwithredbull** [comment]
Please post the contents of your 'Walletd.log' file. Also ensure that TurtleCoind.exe and Walletd.exe are not running already when starting the wallet.

**Comment by Square2k1** [comment]
i can confirm TurtleCoind.exe and Walletd.exe are not running

here is the the log:

2018-Feb-22 08:05:43.809277 INFO    walled v0.3.2.1253 (0.1-g7fcc6ad)
2018-Feb-22 08:05:43.809277 INFO    Starting Payment Gate with local node
2018-Feb-22 08:05:43.809277 INFO    Opening DB in C:\Users\Mining Rig\AppData\Roaming/TurtleCoin/DB
2018-Feb-22 08:05:43.965584 INFO    DB opened in C:\Users\Mining Rig\AppData\Roaming/TurtleCoin/DB
2018-Feb-22 08:05:43.965584 INFO    initializing core
2018-Feb-22 08:05:43.981170 INFO    Importing blocks from blockchain storage
2018-Feb-22 08:05:43.996797 ERROR   Corrupted blockchain. Block with index 205336 and hash 31c7f587bbbfddde82c5b48cf8ea1f5f5719e4a0bd840fe0493b957e7bc1dd60 has previous block hash c61b93fb29038222b82752315157cb3238fffd9937d761827d5b18b58ba141e1, but parent has hash 27dbb04fb018df40e8b97d3376c541475be6349421322abb751021a0983acad0. Resynchronize your daemon please.
2018-Feb-22 08:05:44.012423 INFO    Closing DB.
2018-Feb-22 08:07:09.605020 INFO    walled v0.3.2.1253 (0.1-g7fcc6ad)
2018-Feb-22 08:07:09.608027 INFO    Starting Payment Gate with local node
2018-Feb-22 08:07:09.609531 INFO    Opening DB in C:\Users\Mining Rig\AppData\Roaming/TurtleCoin/DB
2018-Feb-22 08:07:09.715568 INFO    DB opened in C:\Users\Mining Rig\AppData\Roaming/TurtleCoin/DB
2018-Feb-22 08:07:09.721496 INFO    initializing core
2018-Feb-22 08:07:09.735514 INFO    Importing blocks from blockchain storage
2018-Feb-22 08:07:09.753060 ERROR   Corrupted blockchain. Block with index 205336 and hash 31c7f587bbbfddde82c5b48cf8ea1f5f5719e4a0bd840fe0493b957e7bc1dd60 has previous block hash c61b93fb29038222b82752315157cb3238fffd9937d761827d5b18b58ba141e1, but parent has hash 27dbb04fb018df40e8b97d3376c541475be6349421322abb751021a0983acad0. Resynchronize your daemon please.
2018-Feb-22 08:07:09.762084 INFO    Closing DB.

**Comment by Watt3r** [comment]
You have to resync your blockchain. You can bootstrap it with instructions from the discord. Next time please use #help channel in the discord

**Comment by codingwithredbull** [comment]
Thanks @Watt3r . 

Indeed he is correct, your blockchain has been invalidated somehow. You must delete your DB folder and "blockindexes.bin" file in the `%appdata%/TurtleCoin` folder and allow the daemon to resync from the start.

This however can take a long time now, as our chain is growing ever larger. Use these instructions below to bootstrap it and get up faster!
https://github.com/turtlecoin/turtlecoin/wiki/HowToBootstrapBlockchain
