### ISSUE TITLE
Exceptional

### ISSUE THREAD

**Issue by prographo** [turtlecoin/desktop-xamarin#6]
![untitled](https://user-images.githubusercontent.com/11575008/35739766-9b4cc11c-082a-11e8-88a3-44e6aa0cca8f.png)

**Comment by prographo** [comment]
I take it back. The .zip works fine, I ran the .exe

(so why have the .exe there? when it's in the .zip and all correct? -- anyway, s'all good)

**Comment by codingwithredbull** [comment]
.EXE is for updating old clients only, as the description says on the download page
