### ISSUE TITLE
TurtleCoin Wallet Install Issue

### ISSUE THREAD

**Issue by SomeRandomSteve** [turtlecoin/desktop-xamarin#7]
fyi, after dl and install of the windows gui wallet (TurtleWallet.exe) the program goes into a up-dates loop. then after closing it it then opens and asks to open a wallet or create a wallet, either way after that it crashes .

**Comment by codingwithredbull** [comment]
Can i please get the message of the crash? Or symptoms to reproduce?

**Comment by codingwithredbull** [comment]
Please update to newest version to see if your issue remains, this will be closed until issues are posted again.
